# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  github_provider_key: <%= ENV["GITHUB_PROVIDER_KEY"] %>
  github_provider_secret: <%= ENV["GITHUB_PROVIDER_SECRET"] %>

  weibo_provider_key: <%= ENV["WEIBO_PROVIDER_KEY"] %>
  weibo_provider_secret: <%= ENV["WEIBO_PROVIDER_SECRET"] %>
  domain_name: example.com
  secret_key_base: 499ed5cb646ed762eb3ef0c7e897e4faa3e79b683d7e6c83a1d33e79aac0b0b665915c7d457514b4960d8bb8448d80a863caf5c16b851be57a2192f6da202000

test:
  secret_key_base: 3d64e1305376b7cc8621ac595c405e44cdd96ad4c1f7994d637a56311ab775f65f96883d1871b7ae9098f85bebeb8f9f7b88e9586b583fb73e229624bc0af152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  github_provider_key: fe13645ed363073164b3
  github_provider_secret: 4fe343e976889ee8a01a0464f0d9f98f691ee1a6
  weibo_provider_key: 1768351070
  weibo_provider_secret: 2ea8fd692cae5a8c8442638c2daf645f
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: 410c1a4c50d3cbfd7a3c4dba85aec86745269b5d1c462f90322647dd42a170fdd9166978841078564e24c7689608d2056119b7156b75f863005f2ca9b6fb6b97
